#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login_check:
    path:     /login_check
    methods:  [POST]

token:
    path:     /token
    controller: App\Controller\DefaultController::token
    methods:  [POST]

register:
    path:     /register
    controller: App\Controller\DefaultController::register
